ui: tape
browsers:
  - name: chrome
    version: 39..latest
  - name: firefox
    version: 34..latest
  - name: safari
    version: 7..latest
  - name: internet explorer
    version: 9..latest
  - name: iPhone
    version: '8.0..latest'
  - name: ipad
    version: 4.3..latest
  - name: android
    version: 4.0..latest
